### ISSUE TITLE
Missing Glyphicons (Bootstrap)

### ISSUE THREAD

**Issue by DerekFoulk** [verekia/initializr#92]
Initializr (Bootstrap) is missing some glyphicons. The culprit is a missing file in the '/fonts' directory. 'glyphicons-halflings-regular.woff2' should be there, but it isn't.

How to replicate:
- D/L Initializr (Bootstrap)
- Try to use this glyphicon with Initializr (Bootstrap)... '.glyphicon-triangle-right'

Affected OSes/Browsers:
- All

**Comment by verekia** [comment]
I believe these missing icons were added in Bootstrap v3.3.2, and Initializr currently only provides Bootstrap v3.3.1. This particular issue will be fixed when I update it to the latest version. I'll buffer Bootstrap updates a little more before doing that though. So for the moment, please download the latest CSS files and fonts from Bootstrap directly if you need these icons :)
